version: 0.3

project:
 name: "rx-etersoft"
 apt:
   sources:
     - "rpm ftp://server/pub ALTLinux/c7/branch/x86_64 classic"
     - "rpm ftp://server/pub ALTLinux/c7/branch/noarch classic"
     #- "rpm ftp://server/pvt/Etersoft/RX@Etersoft/c7 x86_64/ALTLinux/c7 main"

 project_compose_template: 'docker-compose-systemd.yml.tpl'
 node_compose_template: 'docker-compose-systemd-simple.yml.tpl'
 groups:
   rx:
     nodes:
       rx-etersoft:
         context: "rx-etersoft-$BUILD_ID"
         skip_compose: yes
         image: x64.c7-rx-etersoft
         hostname: "rx-server-$BUILD_ID"
         environment:
           - "SERVICE_NAME=$SERVICE_NAME"
           - "SERVICE_TAGS=rx-etersoft,build-$BUILD_ID"
         ports:
           - "$CI_BUILD_ID:22"
         copy:
           - "rx-test.list:/etc/apt/sources.list.d/"
           - "03-logging.conf:/tmp/"
           - "[0400]guest.sudo:/etc/sudoers.d/guest"

         before_command:
           - epm repolist && epm update
           - epm i --auto rx-etersoft
           - cp -f /tmp/03-logging.conf /etc/nxserver/node.conf.d/
           - chown root:root /etc/sudoers.d/guest
